### ISSUE TITLE
Unhandled exception when resolving deleted video from playlist.

### ISSUE THREAD

**Issue by pcroland** [sorashi/youtube-play#1]
![image](https://user-images.githubusercontent.com/11183274/33236022-75269134-d247-11e7-8734-574b95566205.png)
![image](https://user-images.githubusercontent.com/11183274/33236025-892a38c0-d247-11e7-8c54-513eb5c0aceb.png)

**Comment by sorashi** [comment]
@pcroland Fixed it, download the [new release](../releases/tag/v0.1.1-beta)

**Comment by pcroland** [comment]
Thanks :D
